<?php

drupal_add_css(drupal_get_path('module', 'org_chart') . '/css/org_chart.css');

/**
 * Implements hook_menu().
 */
function org_chart_menu() {
  $items = array();

   $items['admin/config/services/org_chart'] = array(
    'title'             => 'Organization Chart',
    'page callback'     => 'drupal_get_form',
    'page arguments'    => array('org_chart_admin_settings'),
    'access callback'   => 'user_access',
    'access arguments'  => array('administer site configuration'),
    'type'              => MENU_NORMAL_ITEM,
    'file'              => 'org_chart.admin.inc',
  );

  $items['org-chart'] = array(
    'title' => 'Org Chart',
    'page callback' => 'org_chart_page',
    'access callback' => TRUE,
    'expanded' => TRUE,
    'menu_name' => 'main-menu',
  );

  return $items;
}


function org_chart_page() {
  return array(
    '#title' => t('Organization Chart'),
    '#markup' => org_chart_singleManager() . org_chart_getSingleManagerEmployee() . org_chart_hp_logo()
  );
}

/**
 * Implementation of hook_block_info().
 */
function org_chart_block_info() {
  $blocks['org_chart_manager'] = array(
    'info' => t('org_manager'),
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  $blocks['org_chart_employee'] = array(
    'info' => t('org_employee'),
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
//  $blocks['org_chart_assistant'] = array(
//    'info' => t('org_assistant'),
//    'cache' => DRUPAL_CACHE_PER_PAGE,
//  );
  $blocks['hp_logo'] = array(
    'info' => t('hp_logo'),
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  return $blocks;
}

/**
 * Implementation of hook_block_view().
 */
function org_chart_block_view($delta = '') {
    $block['content'] = array();
    switch ($delta) {
        case 'org_chart_manager':
            $block['content'] = org_chart_singleManager();
            break;
        case 'org_chart_employee':
            $block['content'] = org_chart_getSingleManagerEmployee();
            break;
//        case 'org_chart_assistant':
//            $block['content'] = org_chart_getSingleManagerAssistant();
//            break;
        case 'hp_logo':
            $block['content'] = org_chart_hp_logo();
            break;
    }
    return $block;
}

function org_chart_jsonurl() {
    $request = variable_get('org_chart_url');
    if (empty($request)) {
        drupal_set_message(t('Please enter Organization Chart webservices json URL in Configuration Settings.'));
        return FALSE;
    } else {
        $json_url = drupal_http_request($request);
        $details = drupal_json_decode($json_url->data);
        if ($details != '') {
            return $details;
        }
    }
}

function org_chart_getOnlyManagers() {
    $displayManager = array();
    $details = org_chart_jsonurl();
    for ($i = 0; $i < sizeof($details); $i++) {
        $displayManager[$i] = $details[$i]['managerUid'];
    }
    $managerUnique = array_unique($displayManager);
    $comma_separated = implode(",", $managerUnique);
    $managerArry = explode(",", $comma_separated);
    return $managerArry;
}

function org_chart_managerEmployeeSet() {
    $details = org_chart_jsonurl();
    $managerArray = org_chart_getOnlyManagers();
    $managerEmplyeeArrHold = array();
    foreach ($managerArray as $manager) {
        $y = 0;
        for ($i = 0; $i < sizeof($details); $i++) {
            if ($manager == $details[$i]['managerUid'] && $manager != $details[$i]['uid']) {
                if ($details[$i]['picURI'] != NULL) {
                    $img = '<img class="img" src="' . $details[$i]['picURI'] . '"/>';
                } else {
//                  $default_img = drupal_get_path('themes','hp_intra').'/images/user_defaultprofile.png';
                    $img = '<img class="img" src="/sites/all/themes/hp_intra/images/user_defaultprofile.png"/>';
                }
//                if ($details[$i]['jobFamily'] != 'Assistants') {
                    $managerEmplyeeArrHold[$manager][$y] = '';
                    $managerEmplyeeArrHold[$manager][$y] .= '<div class="org_profile"><a class="url" href="' . urlencode($details[$i]['uid']) . '">';
                    $managerEmplyeeArrHold[$manager][$y] .= '<div class="wholeblock"> <div class="memberimage">' . $img . '</div>';
                    foreach ($managerArray as $mngr) {
                        if ($details[$i]['uid'] == $mngr) {
                            $managerEmplyeeArrHold[$manager][$y] .= '<img class="imgSmall" src="/innovation/sites/all/modules/hp/org-chart/images/org_chart_logo.png"/>';
                            break;
                        }
                    }
                    $managerEmplyeeArrHold[$manager][$y] .= '<div><p class="memberName">' . $details[$i]['fullName'] . '</p>';
                    if ($details[$i]['title'] != NULL) {
                        $managerEmplyeeArrHold[$manager][$y] .= $details[$i]['title'] . '<br/>';
                    }
                    if ($details[$i]['state'] == NULL) {
                        $managerEmplyeeArrHold[$manager][$y] .= $details[$i]['country'] . '<br/>';
                    } else {
                        $managerEmplyeeArrHold[$manager][$y] .= $details[$i]['city'] . ', ' . $details[$i]['state'] . '<br/>';
                        $managerEmplyeeArrHold[$manager][$y] .= $details[$i]['country'] . '<br/>';
                    }

                    $managerEmplyeeArrHold[$manager][$y] .= '</div></div></a></div>';
                    $y++;
//                }
            }
        }
    }
    return $managerEmplyeeArrHold;
}

//function org_chart_getSingleManagerAssistantSet(){
//    $details = org_chart_jsonurl();
//    $managerArray = org_chart_getOnlyManagers();
//    $managerEmplyeeArrHold = array();
//    foreach ($managerArray as $manager) {
//        $y = 0;
//        for ($i = 0; $i < sizeof($details); $i++) {
//            if ($manager == $details[$i]['managerUid'] && $manager != $details[$i]['uid']) {
//                if ($details[$i]['picURI'] != NULL) {
//                    $img = '<img class="img" src="' . $details[$i]['picURI'] . '"/>';
//                } else {
////                  $img = '<img class="img" src="drupal_get_path('themes','hp_intra').'/images/user_defaultprofile.png"/>';
//                    $img = '<img class="img" src="/sites/all/themes/hp_intra/images/user_defaultprofile.png"/>';
//                }
//                if ($details[$i]['jobFamily'] == 'Assistants') {
//                    $managerEmplyeeArrHold[$manager][$y] = '';
//                    $managerEmplyeeArrHold[$manager][$y] .= '<div><a class="url" href="/innovation/org-chart/' . urlencode($details[$i]['uid']) . '">';
//                        $managerEmplyeeArrHold[$manager][$y] .= '<div class="wholeblock" style="margin-top: 10px;"> <div class="memberimage">' . $img . '</div>';
//                        $managerEmplyeeArrHold[$manager][$y] .= '<div><p class="memberName">' . $details[$i]['fullName'] . '</p>';
//                         if ($details[$i]['title'] != NULL) {
//                            $managerEmplyeeArrHold[$manager][$y] .= $details[$i]['title'] . '<br/>';
//                        }
//                        if ($details[$i]['state'] == NULL) {
//                            $managerEmplyeeArrHold[$manager][$y] .= $details[$i]['country'] . '<br/>';
//                        } else {
//                            $managerEmplyeeArrHold[$manager][$y] .= $details[$i]['city'] . ', ' . $details[$i]['state'] . '<br/>';
//                            $managerEmplyeeArrHold[$manager][$y] .= $details[$i]['country'] . '<br/>';
//                        }
//                        $managerEmplyeeArrHold[$manager][$y] .= '</div></div></a></div>';
//                        $y++;
//                    }
//                }
//        }
//    }
//    return $managerEmplyeeArrHold;
//}

function org_chart_managerUID_url($managerUID = null) {
    $currenturl = $_SERVER['HTTP_HOST'] . htmlspecialchars($_SERVER['REQUEST_URI']);
    $tokens = explode('/', $currenturl);         //Separate the individual elements
    $managerUID = $tokens[sizeof($tokens) - 1];  //Set the last portion of the URL as $finalargument
    $manager_url = urldecode($managerUID);       //Get the current 'uid' parameter directly from URL
    return $manager_url;
}

function org_chart_getSingleManagerEmployee() {
    $out_put = '';
    $output = array();
    $manager_url = org_chart_managerUID_url();
    $managerEmplyeeArrHold = org_chart_managerEmployeeSet();
    $singleManagerEmployee = array();
    foreach ($managerEmplyeeArrHold as $manager => $value) {
        if ($manager == $manager_url) {
            $u = 0;
            for ($i = 0; $i < sizeof($value); $i++) {
                $singleManagerEmployee[$manager][$u] = $value[$i];
                $u++;
                foreach ($singleManagerEmployee as $employee) {
                    $output = $employee;
                }
            }
        }
    }
    $out_put = implode(' ', $output);
    return $out_put;
}

//function org_chart_getSingleManagerAssistant() {
//    $out_put = '';
//    $output = array();
//    $manager_url = org_chart_managerUID_url();
//    $managerEmplyeeArrHold = org_chart_getSingleManagerAssistantSet();
//    $singleManagerEmployee = array();
//    foreach ($managerEmplyeeArrHold as $manager => $value) {
//        if ($manager == $manager_url) {
//            $u = 0;
//            for ($i = 0; $i < sizeof($value); $i++) {
//                $singleManagerEmployee[$manager][$u] = $value[$i];
//                $u++;
//                foreach ($singleManagerEmployee as $employee) {
//                    $output = $employee;
//                }
//            }
//        }
//    }
//    $out_put = implode(' ', $output);
//    return $out_put;
//}


function org_chart_singleManager(){
    $out_put = '';
    $details = org_chart_jsonurl();
    $currenturl = $_SERVER['HTTP_HOST'] . htmlspecialchars($_SERVER['REQUEST_URI']);
    $tokens = explode('/', $currenturl);  //Separate the individual elements
    $managerUID = $tokens[sizeof($tokens) - 1];
    $manager_url = urldecode($managerUID);

    for ($i = 0; $i < sizeof($details); $i++) {
        if ($manager_url == $details[$i]['uid']) {
            if ($details[$i]['picURI'] != NULL) {
                $img = '<img class="managerimg" src="' . $details[$i]['picURI'] . '"/>';
            } else {
//                  $default_img = drupal_get_path('themes','hp_intra').'/images/user_defaultprofile.png';
                $img = '<img class="managerimg" src="/sites/all/themes/hp_intra/images/user_defaultprofile.png"/>';
            }
            $out_put .= '<div class="manager"><div class="managerimage">' . $img . '</div>';
            $out_put .= '<div><p class="managerName">' . $details[$i]['fullName'] . '</p>';
            if ($details[$i]['title'] != NULL) {
                $out_put .= $details[$i]['title'] . '<br/>';
            } else {
                $out_put .= $details[$i]['jobFamily'] . '<br/>';
            }
            if ($details[$i]['state'] == NULL) {
                $out_put .= $details[$i]['country'] . '<br/>';
            } else {
                $out_put .= $details[$i]['city'] . ', ' . $details[$i]['state'] . '<br/>';
                $out_put .= $details[$i]['country'] . '<br/>';
            }
            $out_put .= '</div></div> </a><br/>';
        }

    }
    return $out_put;
}

function org_chart_hp_logo() {
    $output = '';
    $output = '<img class="hp_img" src="/innovation/sites/all/modules/hp/org-chart/images/hp_logo.png"/>';
    return $output;
}
